protected/models/Digest.php
<?php

/**
 * This is the model class for table "digest".
 *
 * The followings are the available columns in table 'digest':
 * @property integer $id
 * @property integer $idCategory
 * @property string $name
 * @property string $text
 * @property string $time
 * @property string $status
 * @property string $image
 * @property double $avg_rating
 */
class Digest extends CActiveRecord
{
    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Digest the static model class
     */
    const IMAGE_PATH = '/upload/digets/';
    const DEFAULT_IMAGE = '/assets/images/articles-overlay.png';

    public $minRatingFilter = 0;
    public $maxRatingFilter = 5;
    public $id_category = '';
    public $dateStart = '';
    public $dateEnd = '';


    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'digest';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        return array(
            array('name, text', 'required', 'message' => 'Поле {attribute} не может быть пустым'),
            array('name, time, image, status', 'length', 'max' => 255),
            array('avg_rating', 'numerical'),

            array('id, idCategory, name, text, time, status, avg_rating, maxRatingFilter, minRatingFilter, id_category,
             dateStart, dateEnd, onlyMe', 'safe',  'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
// NOTE: you may need to adjust the relation name and the related
// class name for the relations automatically generated below.
        return array();
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'idCategory' => 'Id Category',
            'name' => 'Имя',
            'text' => 'Текст',
            'time' => 'Дате',
            'status' => 'Статус',
            'image' => 'Изображение',
            'avg_rating' => 'Среднему рейтингу',
            'maxRatingFilter' => 'Максимальный рейтинг',
            'minRatingFilter' => 'Минимальный рейтинг',
            'id_category' => 'Категория'
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
// @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('idCategory', $this->idCategory);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('text', $this->text, true);
        $criteria->compare('time', $this->time, true);
        $criteria->compare('status', $this->status, true);

        if($this->id_category != '')
            $criteria->addCondition("idCategory LIKE '%". $this->id_category . "%'");
        $params = array(
            'min_rating' => $this->minRatingFilter,
            'max_rating' => $this->maxRatingFilter,
        );
        if ($this->dateStart != "") {
            $criteria->addCondition('time >= :dateStart');
            $params['dateStart'] = $this->dateStart;
        }
        if ($this->dateEnd != "") {
            $criteria->addCondition('time <= :dateEnd');
            $params['dateEnd']= $this->dateEnd;
        }
        $criteria->addCondition('avg_rating >= :min_rating');
        $criteria->addCondition('avg_rating <= :max_rating');
        $criteria->params = $params;
        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function getImage()
    {
        if (($this->image)&&(file_exists($this->image))) {
            return self::IMAGE_PATH . $this->image;
        } else {
            return self::DEFAULT_IMAGE;
        }
    }

    protected function beforeSave()
    {
        if (parent::beforeSave()) {
            if ($this->isNewRecord) {
                $this->status = 'public';
            }
            return true;
        }
        return false;
    }

}

protected/controllers/DigestController.php
<?php

class DigestController extends CController
{
    public $breadCrumbs;

    public function actionIndex()
    {

        $this->breadCrumbs = array('Дайджест соцсетей');
        $model=new Digest('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['Digest']))
            $model->attributes=$_GET['Digest'];

        //send model object for search
        $this->render('index',array(
                'dataProvider'=>$model->search(),
                'model'=>$model)
        );

    }

    public function actionView(){

        $idDigest = Yii::app()->request->getQuery('id');
        if($idDigest) {
            $this->breadCrumbs = array('Дайджест соцсетей' => Yii::app()->request->baseUrl . '/digest', 'Просмотр статьи');
            $digest = Digest::model()->findByPk($idDigest);
            $this->layout = 'main';
            $this->render('view', array('digest' => $digest));
        } else {
            $this->breadCrumbs = array('Дайджест соцсетей');
            $digests = Digest::model()->findAll();
            $this->layout = 'main';
            $this->render('index', array('digests' => $digests));
        }

    }

    public function actionEdit(){

        $idDigest = Yii::app()->request->getQuery('id');
        if($idDigest) {
            $this->breadCrumbs = array('Дайджест' => Yii::app()->request->baseUrl . '/digest', 'Редактирование статьи');
            $digestModel = Digest::model()->findByPk($idDigest);
            if(User::model()->findByPk(Yii::app()->user->id)->role == 'admin') {
                $categoryModel = new Category();
                $this->performAjaxValidation($digestModel, 'edit-digest');
                $this->performAjaxValidation($categoryModel, 'edit-digest');
                $this->layout = 'main';
                $this->render('edit', array('digestModel' => $digestModel, 'categoryModel' => $categoryModel));
            } else {
                $this->redirect(Yii::app()->request->getBaseUrl(true).'/digest');
            }
        } else {
            $this->breadCrumbs = array('Дайджест');
            $digest = Digest::model()->findAll();
            $this->layout = 'main';
            $this->render('index', array('digest' => $digest));
        }

    }

    public function actionUpdate(){

        if (!Yii::app()->user->isGuest) {
            $digestModel = new Digest();
            $categoryModel = new Category();
            $this->performAjaxValidation($digestModel, 'edit-digest');
            if  (($_POST['Digest'])&&($_POST['Category'])) {
                $digestModel->attributes = $_POST['Digest'];
                $categoryModel->attributes = $_POST['Category'];
                $tmpImage = CUploadedFile::getInstance($digestModel, 'image');
                $filename = '';
                if($tmpImage) {
                    $filename = md5(time() . rand()) . '.' . $tmpImage->getExtensionName();
                    $digestModel->image = $filename;
                    $path = Yii::getPathOfAlias('webroot') . '/upload/digest/' . $filename;
                }
                $digestModel->time = date('Y-m-d H:i:s');
                $idsCategory = implode(',',$categoryModel->name);
                $digestModel->idCategory = $idsCategory;
                if ($digestModel->validate()) {
                    if($tmpImage) {
                        Digest::model()->updateByPk($_POST['Digest']['id'], array('name' => $digestModel->name, 'text' => $digestModel->text, 'image' => $filename, 'idCategory' => $digestModel->idCategory));
                        $tmpImage->saveAs($path);
                    }
                    else {
                        Digest::model()->updateByPk($_POST['Digest']['id'], array('name'=>$digestModel->name,'text'=>$digestModel->text, 'idCategory' => $digestModel->idCategory));
                    }
                    $this->redirect(Yii::app()->request->getBaseUrl(true).'/digest');
                } else
                    print_r($digestModel->getErrors());
            } else
                echo 'error2';
        }
        else{
            $this->redirect(Yii::app()->homeUrl);
        }

    }

    public function actionAdd(){

        if ((!Yii::app()->user->isGuest)&&(User::model()->findByPk(Yii::app()->user->id)->role == 'admin')) {
            $digestModel = new Digest();
            $categoryModel = new Category();
            $this->performAjaxValidation($digestModel, 'add-digest');
            $this->performAjaxValidation($categoryModel, 'add-digest');
            $this->breadCrumbs = array('Дайджест' => Yii::app()->request->baseUrl . '/digest', 'Добавление новой статьи');
            $this->layout = 'main';
            $this->render('add', array('digestModel' => $digestModel, 'categoryModel' => $categoryModel));
        }
        else{
            $this->redirect(Yii::app()->homeUrl);
        }

    }

    public function actionSaveNew(){

        if ((!Yii::app()->user->isGuest)&&(User::model()->findByPk(Yii::app()->user->id)->role == 'admin')) {

            $digestModel = new Digest();
            $categoryModel = new Category();
            $this->performAjaxValidation($digestModel, 'add-digest');
            if (($_POST['Digest']) && ($_POST['Category'])) {
                $digestModel->attributes = $_POST['Digest'];
                $categoryModel->attributes = $_POST['Category'];
                $tmpImage = CUploadedFile::getInstance($digestModel, 'image');
                if ($tmpImage) {
                    $filename = md5(time() . rand()) . '.' . $tmpImage->getExtensionName();
                    $digestModel->image = $filename;
                    $path = Yii::getPathOfAlias('webroot') . '/upload/digest/' . $filename;
                }
                $digestModel->time = date('Y-m-d H:i:s');
                $idsCategory = implode(',',$categoryModel->name);
                $digestModel->idCategory = $idsCategory;
                if ($digestModel->validate()) {
                    $digestModel->save();
                    if ($tmpImage)
                        $tmpImage->saveAs($path);
                    $this->redirect(Yii::app()->request->getBaseUrl(true) . '/digest');
                } else
                    print_r($digestModel->getErrors());
            } else
                echo 'error code: 2';
        }
        else{
            $this->redirect(Yii::app()->homeUrl);
        }

    }

    //function remove the article by id
    //input parameters:
    ////id
    public function actionRemove(){

        if (!Yii::app()->user->isGuest) {
            if (User::model()->findByPk(Yii::app()->user->id)->role == 'admin') {
                $idDigest = Yii::app()->request->getPOST('id');
                Digest::model()->deleteByPk($idDigest);
            }
        }
    }

    public function actionGetDigest(){

        //if (!Yii::app()->user->isGuest) {

        $idCategory = Yii::app()->request->getPOST('idCategory');
        $digestDate = Yii::app()->request->getPOST('digestDate');

        //$idCategory = -1;
        //$digestDate = "2015-10-14";

        $criteria = new CDbCriteria;
        $condition = '';
        if($idCategory != -1)
            $condition .= "idCategory = ". $idCategory . " AND";
        if($digestDate != '')
            $condition .= " time LIKE '". $digestDate . "%'";

        $condition = preg_replace('/AND$/','',$condition);

        $criteria->condition=$condition;

        $digest = Digest::model()->findAll($criteria);
        $digestForJson = array();

        foreach ($digest as $key) {
            $name = 'Администратор';
            $digest = array(
                'id' => $key->id,
                'author' => $name,
                'name' => $key->name,
                'text' => $key->text,
                'time' => $key->time,
                'image' => $key->image,
            );
            array_push($digestForJson, $digest);
        }
        echo json_encode($digestForJson);
        //}

    }

    protected function performAjaxValidation($model, $form){
        if (isset($_POST['ajax']) && $_POST['ajax'] === $form) {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

    public function actionSetrating() {
        if (Yii::app()->request->isAjaxRequest){
            $id_elem = Yii::app()->request->getParam('id_elem');
            $type_elem = Yii::app()->request->getParam('type_elem');
            $value = Yii::app()->request->getParam('value');
            RatingHelper::setRating($id_elem,$type_elem,$value);
            echo $this->renderPartial('_rating',['id'=>$id_elem,'type_elem'=>$type_elem]);
        }
    }

}

protected/views/digest/_rating.php
<? $this->widget('RatingWidget',['elem_id'=>$id,'elem_type'=>$type_elem,'avg'=>RatingHelper::getRating($id,$type_elem)]) ?>

protected/views/digest/_search.php
<?php
/* @var $this TestController */
/* @var $model Article */
/* @var $form CActiveForm */
?>

<div class="wide form">
    <?php $form = $this->beginWidget('CActiveForm', array(
        'action' => Yii::app()->createUrl($this->route),
        'method' => 'get',
    )); ?>
    <div class="row form-group">
        <!-- condition is for do not display fields which in this condition -->
        <?php if(false){ ?>
            <div class="col-md-3">
                <p>Дата с</p>
                <?php
                $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'name' => 'dateStart',
                    'model' => $model,
                    'attribute' => 'dateStart',
                    'language' => 'ru',
                    'options' => array(
                        'dateFormat' => 'yy-mm-dd',
                        'class' => 'fieldInput',
                        'showAnim' => 'fold',
                    ),
                    'htmlOptions' => array(
                        'class' => 'fieldInput',
                        'id' => 'dateStart',
                    ),
                )); ?>
            </div>
            <div class="col-md-3">
                <p>Рейтинг с</p>
                <? echo CHtml::activeDropDownList($model, 'minRatingFilter', array(0 => '0', 1 => '1', 2 => '2', 3 => '3', 4 => '4'), array(
                    'class' => 'fieldInput',
                )); ?>
            </div>
            <div class="col-md-3">
                <p>Категория</p>
                <?php
                echo CHtml::activeDropDownList($model, 'id_category', CHtml::listData(Category::model()->findAll(), 'id', 'name', 'category'), array(
                    'class' => 'fieldInput',
                    'prompt' => 'Не выбрана',
                ));
                ?>
            </div>
        <?php } ?>
        <? if(!Yii::app()->user->IsGuest) {
            if(User::model()->findByPk(Yii::app()->user->id)->role == 'admin'){ ?>
            <div class="col-md-12">
                <? echo CHtml::link('Добавить дайджест',array('digest/add') ,
                    array(
                        'style' => 'margin-top:27px;display:block;width:200px;text-decoration:none;color:#fff;float:right;padding:5px 16px;background-color:#456BA5;',
                        'class' => 'help-home bg-liteBlue'
                    )); ?>
            </div>
        <?php } } ?>
    </div>
    <div class="row">
        <?php if(false) { ?>
        <div class="col-md-3">
            <p>Дата по</p>
            <?php
            $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                'name' => 'dateEnd',
                'model' => $model,
                'attribute' => 'dateEnd',
                'language' => 'ru',
                'options' => array(
                    'dateFormat' => 'yy-mm-dd',
                    'class' => 'fieldInput',
                    'showAnim' => 'fold',
                ),
                'htmlOptions' => array(
                    'class' => 'fieldInput',
                    'id' => 'dateEnd',
                ),
            )); ?>
        </div>
        <div class="col-md-3">
            <p>Рейтинг по</p>
            <? echo CHtml::activeDropDownList($model, 'maxRatingFilter', array(1 => '1', 2 => '2', 3 => '3', 4 => '4', 5 => '5'), array(
                'class' => 'fieldInput',
            )); ?>
        </div>
    <?php if (!Yii::app()->user->isGuest && Yii::app()->user->id) { ?>
        <div class="col-md-3">
            <p>Автор дайджеста</p>
            <?php
            echo CHtml::activeDropDownList($model, 'onlyMe', array('0' => 'Любой', '1' => 'Только я'), array(
                'class' => 'fieldInput',
            ));
            ?>
        </div>
    <? } ?>
    <? if(!Yii::app()->user->IsGuest) { ?>
        <div class="col-md-3">
            <?php } else { ?>
            <div class="col-md-3 col-md-push-3">
                <?php } ?>
                <?php echo CHtml::submitButton('Поиск',
                    array(
                        'style' => 'font-family:MyriadProRegular;margin-top:20px;border:medium none;width:200px;float:right;text-align:center;',
                        'class' => 'help-home bg-liteRed'
                    )); ?>
            </div>
            <?php } ?>
        </div>
        <?php $this->endWidget(); ?>
    </div>

protected/views/digest/_view.php
<?php
/* @var $this TestController */
/* @var $data Article */
?>
<div class="row article" id="digest-<?= $data->id; ?>">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-11 article-author"><? ?></div>
            <div class="col-md-1 article-author"></div>
        </div>
        <div class="row form-group">
            <a href="/digest/<?=$data->id?>">
                <div class="col-md-10 article-head no-padding"><?= $data->name ?></div>
                <div class="col-md-2 text-r no-padding"><?= date('d-m-Y',strtotime($data->time)) ?></div>
            </a>
            <?php
            if(isset(Yii::app()->user->id)) {
            if( User::model()->findByPk(Yii::app()->user->id)->role == 'admin') {
                ?>
                <div class="col-md-1 text-r"><a href="/digest/edit/<?= $data->id; ?>"><i class="fa fa-pencil-square-o"></i></a>
                    <i class="fa fa-times" onclick="removeArticle(this, 1)" data-id="<?= $data->id; ?>"></i></div>
            <?php
            } }
            ?>
        </div>
        <div class="row article-text">
            <div class="col-md-9 no-padding">
                <?= $data->text ?>
            </div>
            <!--<div class="col-md-2 rating-div" style="text-align: left; margin-left: 17px;" onclick="return false;">-->
                <? //$this->widget('RatingWidget',['elem_id' => $data->id,'elem_type' => 'digest','avg' => RatingHelper::getRating($data->id, 'digest')]); ?>
            <div class="col-md-2">
            </div>
        </div>
    </div>
</div>
<script src="/assets/scripts/articles.js"></script>

protected/views/digest/add.php
<div id="postAdvert" class="col-md-10">
    <?php $formDigest = $this->beginWidget("CActiveForm", array(
        'id' => 'add-digest',
        'action' => Yii::app()->request->baseUrl . '/digest/saveNew',
        'method' => 'post',
//        'enableAjaxValidation' => true,
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
            'validateOnChange' => true
        ),
        'htmlOptions' => array(
            'enctype' => 'multipart/form-data',
            'autocomplete' => 'off',
            'onsubmit' => 'crutchForCKEditor();return true',
        ),
    )); ?>
    <div class="form-group row">
        <div class="col-md-2">
            <?= $formDigest->labelEx($digestModel, 'name') ?>
        </div>
        <div class="col-md-8">
            <?= $formDigest->textField($digestModel, 'name', array('class' => 'fieldInput', 'placeholder' => 'Новая статья')); ?>
            <?= $formDigest->error($digestModel, 'name', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            Категория
        </div>
        <div class="col-md-8">
            <?= $formDigest->dropDownList($categoryModel, 'name', CHtml::listData(Category::model()->findAll(), 'id', 'name', 'category'), array('class' => 'fieldInput', 'multiple' => 'multiple')); ?>
            <?= $formDigest->error($categoryModel, 'name', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            <?= $formDigest->labelEx($digestModel, 'text') ?>
        </div>
        <div class="col-md-8">
            <?= $formDigest->textArea($digestModel, 'text', array('class' => 'fieldInput')); ?>
            <?= $formDigest->error($digestModel, 'text', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <?= CHtml::submitButton('Сохранить статью', array('class' => 'button1 button1reg', 'id'=>'digestSubmit')); ?>
        </div>
    </div>
    <?php $this->endWidget(); ?>
</div>
<script src="//cdn.ckeditor.com/4.5.4/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('Digest[text]');
    var crutchForCKEditor = function(){
        var abc = document.getElementsByTagName('iframe')[0].contentDocument;
        var abc2 = abc.childNodes[1];
        var text = abc2.childNodes[1].childNodes[0].innerHTML;
        if(text != '<br>')
            $('#Digest_text').val(text);
    }
</script>

protected/views/digest/edit.php
<div id="postAdvert" class="col-md-10">
    <?php $formDigest = $this->beginWidget("CActiveForm", array(
        'id' => 'edit-digest',
        'action' => Yii::app()->request->baseUrl . '/digest/update',
        'method' => 'post',
//        'enableAjaxValidation' => true,
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
            'validateOnChange' => true
        ),
        'htmlOptions' => array(
            'enctype' => 'multipart/form-data',
            'autocomplete' => 'off',
//            'onsubmit' => 'return true',
        ),
    )); ?>
    <div class="form-group row">
        <div class="col-md-2">
            <?= $formDigest->labelEx($digestModel, 'name') ?>
        </div>
        <div class="col-md-8">
            <?= $formDigest->textField($digestModel, 'name', array('class' => 'fieldInput', 'placeholder' => 'О сайте')); ?>
            <?= $formDigest->error($digestModel, 'name', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            Категория
        </div>
        <div class="col-md-8">
            <?php
            array($digestModel->idCategory => array('selected'=>true));
            $arrayIdCategories = explode(',',$digestModel->idCategory);
            $arrayCategories = array();
            for($i=0;$i<count($arrayIdCategories);$i++){
                $arrayCategories[$arrayIdCategories[$i]] = array('selected'=>true);
            }
            ?>
            <?= $formDigest->dropDownList($categoryModel, 'name', CHtml::listData(Category::model()->findAll(), 'id', 'name', 'category'), array('class' => 'fieldInput', 'multiple'=>'multiple' , 'options' => $arrayCategories)); ?>
            <?= $formDigest->error($categoryModel, 'name', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            <?= $formDigest->labelEx($digestModel, 'text') ?>
        </div>
        <div class="col-md-8">
            <?= $formDigest->textArea($digestModel, 'text', array('class' => 'fieldInput')); ?>
            <?= $formDigest->error($digestModel, 'text', array('class' => 'text-red')) ?>
        </div>
    </div>
    <?= $formDigest->hiddenField($digestModel, 'id', array('class' => 'fieldInput', 'value'=>$digestModel->id)); ?>
    <div class="form-group row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <?= CHtml::submitButton('Сохранить статью', array('class' => 'button1 button1reg')); ?>
        </div>
    </div>
    <?php $this->endWidget(); ?>
</div>
<script src="//cdn.ckeditor.com/4.5.4/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('Digest[text]');
</script>

protected/views/digest/index.php
<?php
/* @var $this TestController */
/* @var $dataProvider CActiveDataProvider */

?>
<link href='<?= Yii::app()->request->baseUrl ?>/assets/styles/rating.css' media="screen" rel="stylesheet"
      type="text/css"/>
<script type="text/javascript" src='<?= Yii::app()->request->baseUrl ?>/assets/scripts/rating.js'></script>
<? Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
$.fn.yiiListView.update('digestlistview', {
//this entire js section is taken from admin.php. w/only this line diff
data: $(this).serialize()
});
return false;
});
");
?>
<div id="postAdvert" class="col-md-10">
<?php  $this->renderPartial('_search',array(
    'model'=>$model,
)); ?>

<span id="listOfDigest">
<?php
$dataProvider->sort->defaultOrder='time DESC';
$this->widget('zii.widgets.CListView', array(
    'dataProvider' => $dataProvider,
    'itemView' => '_view',
    'id'=>'digestlistview',
    'template'=>'{sorter}{items}{pager}',
    /*
    'sortableAttributes' => array(
        'time',
        'avg_rating'
    ),
    */
));
?>
</span>
</div>

protected/views/digest/view.php
<div id="postAdvert" class="col-md-10 articleDescription">
    <div class="row form-group no-margin">
        <div class="col-md-12">
            <div class="row form-group">
                <div class="col-md-10 article-author">
                    <?php
                    echo 'Администратор';
                    ?>
                </div>
                <div class="col-md-2 text-r no-padding">
                    <?= date('d-m-Y',strtotime($digest->time)) ?>
                </div>
                <?php
                if (!Yii::app()->user->isGuest) {
                    if (User::model()->findByPk(Yii::app()->user->id)->role == 'admin') {
                        ?>
                        <div class="col-md-1 text-r"><a href="/digest/edit/<?= $digest->id; ?>"><i
                                    class="fa fa-pencil-square-o"></i></a>
                            <i class="fa fa-times" onclick="removeArticle(this, 1)" data-id="<?= $digest->id; ?>"></i>
                        </div>
                    <?php
                    }
                }
                ?>
            </div>
            <div class="row">
                <div class="col-md-12 no-padding">
                    <?php
                    $categories = "";
                    if($digest->idCategory) {
                        foreach (explode(',',$digest->idCategory) as $key) {
                            $categories .= Category::model()->findByPk($key)->name . ',';
                        }
                    }
                    $categories = substr($categories,0,-1);
                    ?>
                    Категория: <?= $categories; ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 no-padding" style="font-size:18pt;">
                    <?= $digest->name ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?= $digest->text ?>
        </div>
    </div>
</div>
<script src="/assets/scripts/articles.js"></script>