protected/models/Article.php
<?php

/**
 * This is the model class for table "article".
 *
 * The followings are the available columns in table 'article':
 * @property integer $id
 * @property integer $idUser
 * @property string $name
 * @property string $text
 * @property integer $idCategory
 * @property string $time
 * @property string $status
 * @property string $image
 * @property double $avg_rating
 *
 */
class Article extends CActiveRecord
{
    const IMAGE_PATH = '/upload/articles/';
    const DEFAULT_IMAGE = '/assets/images/articles-overlay.png';
    /**
     * @return string the associated database table name
     */
    public $minRatingFilter = 0;
    public $maxRatingFilter = 5;
    public $id_category = '';
    public $dateStart = '';
    public $dateEnd = '';
    public $onlyMe = 0;

    public function tableName()
    {
        return 'article';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
// NOTE: you should only define rules for those attributes that
// will receive user inputs.
        return array(
            array('name, text', 'required', 'message' => 'Поле {attribute} не может быть пустым'),
            array('idUser', 'numerical', 'integerOnly' => true),
            array('avg_rating', 'numerical'),
            array('name, time, image, status, idCategory', 'length', 'max' => 255),
// The following rule is used by search().
// @todo Please remove those attributes that should not be searched.
            array('id, idUser, name, text, idCategory, time, status,
image, avg_rating, maxRatingFilter, minRatingFilter, id_category,
dateStart, dateEnd, onlyMe',
                'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
// NOTE: you may need to adjust the relation name and the related
// class name for the relations automatically generated below.
        return array(//'user' => array(self::HAS_ONE, 'User', 'id'),
            //'category' => array(self::HAS_MANY, 'Category', 'id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'idUser' => 'Id User',
            'name' => 'Заголовок статьи',
            'text' => 'Текст',
            'idCategory' => 'Id Category',
            'time' => 'Дате',
            'status' => 'Status',
            'image' => 'Изображение',
            'avg_rating' => 'Среднему рейтингу',
            'maxRatingFilter' => 'Максимальный рейтинг',
            'minRatingFilter' => 'Минимальный рейтинг',
            'id_category' => 'Категория'
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
// @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('text', $this->text, true);
        $criteria->compare('idCategory', $this->idCategory);
        $criteria->compare('time', $this->time, true);
        $criteria->compare('status', $this->status, true);
        $criteria->compare('idUser', $this->idUser);

// todo Переделать это говно
        if($this->id_category != '')
            $criteria->addCondition("idCategory LIKE '%". $this->id_category . "%'");
        $params = array(
            'min_rating' => $this->minRatingFilter,
            'max_rating' => $this->maxRatingFilter,
        );
        if ($this->onlyMe != 0) {
            $criteria->addCondition('idUser = :idUser');
            $params['idUser'] = Yii::app()->user->id;
        }
        if ($this->dateStart != "") {
            $criteria->addCondition('time >= :dateStart');
            $params['dateStart'] = $this->dateStart;
        }
        if ($this->dateEnd != "") {
            $criteria->addCondition('time <= :dateEnd');
            $params['dateEnd']= $this->dateEnd;
        }

        $criteria->addCondition('avg_rating >= :min_rating');
        $criteria->addCondition('avg_rating <= :max_rating');
        $criteria->params = $params;

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Article the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    protected function beforeSave()
    {
        if (parent::beforeSave()) {
            if ($this->isNewRecord) {
                $this->status = 'public';
            }
            return true;
        }
        return false;
    }

    public function getImage()
    {
        if (($this->image)&&(file_exists($this->image))) {
            return self::IMAGE_PATH . $this->image;
        } else {
            return self::DEFAULT_IMAGE;
        }
    }


    public static function getCountArticle($date)
    {
        $criteria = new CDbCriteria;
        $criteria->compare('time', $date, true);
        $count = self::model()->find($criteria)->count;
        return $count == null ? 0 : $count;
    }
}

protected/controllers/ArticlesController.php
<?php

class ArticlesController extends CController
{
    public $breadCrumbs;

    public function actionTest()
    {
        $this->breadCrumbs = array('Статьи');
        $this->layout = 'main';
        $dataProvider = new CActiveDataProvider('Article');
        $this->render('test/index', array(
            'dataProvider' => $dataProvider,
        ));
    }

    public function actionIndex(){

        $idCategory = Yii::app()->request->getQuery('category');

        $this->breadCrumbs = array('Статьи');

        if(isset($idCategory)){

            $criteria = new CDbCriteria;
            $criteria->addCondition('idCategory = :idCategory');
            $criteria->params[':idCategory'] = $idCategory;
            $dataProvider = new CActiveDataProvider('Article',array(
                'criteria' => $criteria
            ));

            $param['dataProvider'] = $dataProvider;

            //send model object for search
            $this->render('index', $param);

        } else {
            $model = new Article('search');
            $model->unsetAttributes();  // clear any default values
            //if(isset($_GET['Article']))
            //$model->attributes=$_GET['Article'];

            //send model object for search
            $this->render('index', array(
                    'dataProvider' => $model->search(),
                    'model' => $model)
            );
        }
    }

    public function actionList(){

        $idSection = Yii::app()->request->getQuery('id');

        $this->breadCrumbs = array('Статьи');

        if(isset($idSection)){

            $section=Section::model()->findByPk($idSection);
            $categories = $section->category;

            $articles = $categories[0]->getArticles();

            $criteria = new CDbCriteria;
            $criteria->addCondition('idSection = '.$idSection);
            //$criteria->param(array(':idSection'=> $idSection));

            $section = new CActiveDataProvider('Section',array(
                'criteria' => $criteria
            ));

            $article_ids = array();
            foreach($articles as $article){
                $article_ids[] = $article->id;
            }

            $criteria2 = new CDbCriteria;
            $criteria2->addCondition('id in ('.implode(',',$article_ids).')');

            $articles = new CActiveDataProvider('Article',array(
                'criteria' => $criteria2
            ));

            //die(var_dump($articles));

            $param['articles'] = $articles;

            //send model object for search
            $this->render('index', $param);
        }
    }

    public function actionView(){

        $idArticle = Yii::app()->request->getQuery('id');
        if($idArticle) {
            $this->breadCrumbs = array('Статьи' => Yii::app()->request->baseUrl . '/sections', 'Просмотр статьи');
            $article = Article::model()->findByPk($idArticle);
            $this->layout = 'main';
            $this->render('view', array('article' => $article));
        } else {
            $this->breadCrumbs = array('Статьи');
            $articles = Article::model()->findAll();
            $this->layout = 'main';
            $this->render('index', array('articles' => $articles));
        }

    }

    public function actionEdit(){

        $idArticle = Yii::app()->request->getQuery('id');
        if($idArticle) {
            $this->breadCrumbs = array('Статьи' => Yii::app()->request->baseUrl . '/sections', 'Редактирование статьи');
            $articleModel = Article::model()->findByPk($idArticle);
            if(($articleModel->idUser == Yii::app()->user->id)||( User::model()->findByPk(Yii::app()->user->id)->role == 'admin')) {
                $categoryModel = new Category();
                $this->performAjaxValidation($articleModel, 'edit-article');
                $this->performAjaxValidation($categoryModel, 'edit-article');
                $this->layout = 'main';
                $this->render('edit', array('articleModel' => $articleModel, 'categoryModel' => $categoryModel));
            } else {
                $this->redirect(Yii::app()->request->getBaseUrl(true).'/articles');
            }
        } else {
            $this->breadCrumbs = array('Статьи');
            $articles = Article::model()->findAll();
            $this->layout = 'main';
            $this->render('index', array('articles' => $articles));
        }

    }

    public function actionUpdate(){

        if (!Yii::app()->user->isGuest) {
            $articleModel = new Article();
            $categoryModel = new Category();
            $this->performAjaxValidation($articleModel, 'edit-article');
            if  (($_POST['Article'])&&($_POST['Category'])) {
                $articleModel->attributes = $_POST['Article'];
                $categoryModel->attributes = $_POST['Category'];
                $tmpImage = CUploadedFile::getInstance($articleModel, 'image');
                $filename = '';
                if($tmpImage) {
                    $filename = md5(time() . rand()) . '.' . $tmpImage->getExtensionName();
                    $articleModel->image = $filename;
                    $path = Yii::getPathOfAlias('webroot') . '/upload/articles/' . $filename;
                }
                $articleModel->idUser = Yii::app()->user->id;
                $articleModel->time = date('Y-m-d H:i:s');
                $idsCategory = $_POST['Category'];
                $categoriesString = array();
                foreach($idsCategory['name'] as $idCategory){
                    array_push($categoriesString, '@'. $idCategory . '@');
                }
                $idsCategory = implode(',',$categoriesString);
                $articleModel->idCategory = $idsCategory;
                if ($articleModel->validate()) {
                    if($tmpImage) {
                        Article::model()->updateByPk($_POST['Article']['id'], array('name' => $articleModel->name, 'text' => $articleModel->text, 'image' => $filename, 'idCategory' => $articleModel->idCategory));
                        $tmpImage->saveAs($path);
                    }
                    else {
                        Article::model()->updateByPk($_POST['Article']['id'], array('name'=>$articleModel->name,'text'=>$articleModel->text, 'idCategory' => $articleModel->idCategory));
                    }
                    $this->redirect(Yii::app()->request->getBaseUrl(true).'/sections');
                } else
                    print_r($articleModel->getErrors());
            } else
                echo 'error2';
        }
        else{
            $this->redirect(Yii::app()->homeUrl);
        }

    }

    public function actionAdd(){

        if (!Yii::app()->user->isGuest) {
            $articleModel = new Article();
            $categoryModel = new Category();
            $this->performAjaxValidation($articleModel, 'add-article');
            $this->performAjaxValidation($categoryModel, 'add-article');
            $this->breadCrumbs = array('Статьи' => '/sections', 'Добавление новой статьи');
            $this->layout = 'main';
            $this->render('add', array('articleModel' => $articleModel, 'categoryModel' => $categoryModel));
        }
        else{
            $this->redirect(Yii::app()->homeUrl);
        }

    }

    public function actionSaveNew(){

        if (!Yii::app()->user->isGuest) {
            $articleModel = new Article();
            $categoryModel = new Category();
            $this->performAjaxValidation($articleModel, 'add-article');
            if (($_POST['Article'])&&($_POST['Category'])) {
                $articleModel->attributes = $_POST['Article'];
                $categoryModel->attributes = $_POST['Category'];
                $tmpImage = CUploadedFile::getInstance($articleModel, 'image');
                if($tmpImage) {
                    $filename = md5(time() . rand()) . '.' . $tmpImage->getExtensionName();
                    $articleModel->image = $filename;
                    $path = Yii::getPathOfAlias('webroot') . '/upload/articles/' . $filename;
                }
                $articleModel->idUser = Yii::app()->user->id;
                $articleModel->time = date('Y-m-d H:i:s');
                $idsCategory = array();
                foreach($categoryModel->name as $categoryName){
                    array_push($idsCategory, '@' . $categoryName . '@');
                }
                $idsCategoryStr = implode(',',$idsCategory);
                $articleModel->idCategory = $idsCategoryStr;
                if ($articleModel->validate()) {
                    $articleModel->save();
                    if($tmpImage)
                        $tmpImage->saveAs($path);
                    $this->redirect(Yii::app()->request->getBaseUrl(true).'/sections');
                } else
                    print_r($articleModel->getErrors());
            } else
                echo 'error code: 2';
        }
        else{
            $this->redirect(Yii::app()->homeUrl);
        }

    }

    //function remove the article by id
    //input parameters:
    ////id
    public function actionRemove(){

        if (!Yii::app()->user->isGuest) {
            $idArticle = Yii::app()->request->getPOST('id');
            Article::model()->deleteByPk($idArticle);
        }
    }

    public function actionGetArticles(){

        //if (!Yii::app()->user->isGuest) {

            $idCategory = Yii::app()->request->getPOST('idCategory');
            $userId = Yii::app()->request->getPOST('userId');
            $articleDate = Yii::app()->request->getPOST('articleDate');
            $sorting = Yii::app()->request->getPOST('sorting');
            $criteria = new CDbCriteria;
            $condition = '';

            if($idCategory != -1)
                $condition .= "idCategory LIKE '%". $idCategory . "%' AND";
            if($userId != -1)
                $condition .= " idUser = ". $userId . " AND";
            if($articleDate != '')

protected/views/articles/_search.php
<?php
/* @var $this TestController */
/* @var $model Article */
/* @var $form CActiveForm */
?>

<div class="wide form">
    <?php $form = $this->beginWidget('CActiveForm', array(
        'action' => Yii::app()->createUrl($this->route),
        'method' => 'get',
    )); ?>
    <div class="row form-group">
        <!-- condition is for do not display fields which in this condition -->
        <?php if(false){ ?>
            <div class="col-md-3">
                <p>Дата с</p>
                <?php
                $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'name' => 'dateStart',
                    'model' => $model,
                    'attribute' => 'dateStart',
                    'language' => 'ru',
                    'options' => array(
                        'dateFormat' => 'yy-mm-dd',
                        'class' => 'fieldInput',
                        'showAnim' => 'fold',
                    ),
                    'htmlOptions' => array(
                        'class' => 'fieldInput',
                        'id' => 'dateStart',
                    ),
                )); ?>
            </div>
            <div class="col-md-3">
                <p>Рейтинг с</p>
                <? echo CHtml::activeDropDownList($model, 'minRatingFilter', array(0 => '0', 1 => '1', 2 => '2', 3 => '3', 4 => '4'), array(
                    'class' => 'fieldInput',
                )); ?>
            </div>
            <div class="col-md-3">
                <p>Категория</p>
                <?php
                echo CHtml::activeDropDownList($model, 'id_category', CHtml::listData(Category::model()->findAll(), 'id', 'name', 'category'), array(
                    'class' => 'fieldInput',
                    'prompt' => 'Не выбрана',
                ));
                ?>
            </div>
        <?php } ?>
        <? if(!Yii::app()->user->IsGuest) { ?>
        <div class="col-md-12">
            <? echo CHtml::link('Добавить статью',array('articles/add') ,
                array(
                    'style' => 'margin-top:27px;display:block;width:200px;text-decoration:none;color:#fff;float:right;text-align:center;',
                    'class' => 'help-home bg-liteBlue'
                )); ?>
        </div>
        <?php } ?>
    </div>
    <div class="row">
        <?php if(false) { ?>
            <div class="col-md-3">
                <p>Дата по</p>
                <?php
                $this->widget('zii.widgets.jui.CJuiDatePicker', array(
                    'name' => 'dateEnd',
                    'model' => $model,
                    'attribute' => 'dateEnd',
                    'language' => 'ru',
                    'options' => array(
                        'dateFormat' => 'yy-mm-dd',
                        'class' => 'fieldInput',
                        'showAnim' => 'fold',
                    ),
                    'htmlOptions' => array(
                        'class' => 'fieldInput',
                        'id' => 'dateEnd',
                    ),
                )); ?>
            </div>
            <div class="col-md-3">
                <p>Рейтинг по</p>
                <? echo CHtml::activeDropDownList($model, 'maxRatingFilter', array(1 => '1', 2 => '2', 3 => '3', 4 => '4', 5 => '5'), array(
                    'class' => 'fieldInput',
                )); ?>
            </div>
            <?php if (!Yii::app()->user->isGuest && Yii::app()->user->id) { ?>
                <div class="col-md-3">
                    <p>Автор статей</p>
                    <?php
                    echo CHtml::activeDropDownList($model, 'onlyMe', array('0' => 'Любой', '1' => 'Только я'), array(
                        'class' => 'fieldInput',
                    ));
                    ?>
                </div>
            <? } ?>
            <? if(!Yii::app()->user->IsGuest) { ?>
            <div class="col-md-3">
                <?php } else { ?>
            <div class="col-md-3 col-md-push-3">
                <?php } ?>
                <?php echo CHtml::submitButton('Поиск',
                    array(
                        'style' => 'font-family:MyriadProRegular;margin-top:20px;border:medium none;width:200px;float:right;text-align:center;',
                        'class' => 'help-home bg-liteRed'
                    )); ?>
            </div>
        <?php } ?>
    </div>
    <?php $this->endWidget(); ?>
</div>

protected/views/articles/_view.php
<?php
/* @var $this TestController */
/* @var $data Article */

?>
<div class="row article">
    <div class="col-md-2 no-padding">
        <?php
        $image = Yii::app()->request->baseUrl.'/assets/images/articles-overlay.png';
        if($data->image)
            if($data->image != '')
                $image = Yii::app()->request->baseUrl.'/upload/articles/' . $data->image;
        ?>
        <div class="article-img" style="background-image:url('<?= $image; ?>')"></div>
    </div>
    <div class="col-md-10">
        <div class="row">
            <div class="col-md-11 article-author"><? ?></div>
            <div class="col-md-1 article-author"></div>
        </div>
        <div class="row form-group">
            <a href="/articles/<?=$data->id?>">
                <div class="col-md-10 article-head no-padding" style="padding-left: 14px;">
                    <?= $data->name ?>
                </div>
                <div class="col-md-2 text-r no-padding"><?= date('d-m-Y',strtotime($data->time)) ?></div>
            </a>
            <?php
                $articleModel = Article::model()->findByPk($data->id);
                $idUser = 0;
                if(isset(Yii::app()->user->id)) {
                    $idUser = Yii::app()->user->id;
                    if(($articleModel->idUser == $idUser)||( User::model()->findByPk($idUser)->role == 'admin')) {
                        ?>
                        <div class="col-md-1 text-r">
                            <a href="/articles/edit/<?= $data->id; ?>"><i class="fa fa-pencil-square-o"></i></a>
                            <i class="fa fa-times" onclick="removeArticle(this, 0)" data-id="<?= $data->id; ?>"></i></div>
                        <?php
                    }
                }
            ?>
        </div>
        <div class="row article-text">
            <div class="col-md-9 no-padding" style="margin-left: 14px;">
                <?= $data->text ?>
            </div>
            <!--<div class="col-md-2 rating-div" style="text-align: left; margin-left: 18px;" onclick="return false;">-->
                <? //$this->widget('RatingWidget',['elem_id' => $data->id,'elem_type' => 'article','avg' => RatingHelper::getRating($data->id, 'article')]); ?>
            <div class="col-md-2">
            </div>
        </div>
    </div>
</div>
<script src="/assets/scripts/articles.js"></script>

protected/views/articles/add.php
<div id="postAdvert" class="col-md-10">
    <?php $formArticle = $this->beginWidget("CActiveForm", array(
        'id' => 'add-article',
        'action' => Yii::app()->request->baseUrl . '/articles/saveNew',
        'method' => 'post',
//        'enableAjaxValidation' => true,
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
            'validateOnChange' => true
        ),
        'htmlOptions' => array(
            'enctype' => 'multipart/form-data',
            'autocomplete' => 'off',
            'onsubmit' => 'crutchForCKEditor();return true',
        ),
    )); ?>
    <div class="form-group row">
        <div class="col-md-2">
            <?= $formArticle->labelEx($articleModel, 'name') ?>
        </div>
        <div class="col-md-8">
            <?= $formArticle->textField($articleModel, 'name', array('class' => 'fieldInput', 'placeholder' => 'О сайте')); ?>
            <?= $formArticle->error($articleModel, 'name', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            <?= $formArticle->labelEx($articleModel, 'image'); ?>
        </div>
        <div class="col-md-8">
            <div id="image" class="fieldInput">
                <?= $formArticle->fileField($articleModel, 'image'); ?>
            </div>
            <?= $formArticle->labelEx($articleModel, 'Размер картинки не может превышать 5 MB') ?>
            <?= $formArticle->error($articleModel, 'image', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            Категория
        </div>
        <div class="col-md-8">
            <?= $formArticle->dropDownList($categoryModel, 'name', CHtml::listData(Category::model()->findAll(), 'id', 'name', 'category'), array('class' => 'fieldInput', 'multiple' => 'multiple')); ?>
            <?= $formArticle->error($categoryModel, 'name', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            <?= $formArticle->labelEx($articleModel, 'text') ?>
        </div>
        <div class="col-md-8">
            <?= $formArticle->textArea($articleModel, 'text', array('class' => 'fieldInput')); ?>
            <?= $formArticle->error($articleModel, 'text', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <?= CHtml::submitButton('Сохранить статью', array('class' => 'button1 button1reg')); ?>
        </div>
    </div>
    <?php $this->endWidget(); ?>
</div>
<script src="//cdn.ckeditor.com/4.5.4/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('Article[text]');
    var crutchForCKEditor = function(){
        var abc = document.getElementsByTagName('iframe')[0].contentDocument;
        var abc2 = abc.childNodes[1];
        var text = abc2.childNodes[1].childNodes[0].innerHTML;
        if(text != '<br>')
            $('#Article_text').val(text);
    }
</script>

protected/views/articles/edit.php
<div id="postAdvert" class="col-md-10">
    <?php $formArticle = $this->beginWidget("CActiveForm", array(
        'id' => 'edit-article',
        'action' => Yii::app()->request->baseUrl . '/articles/update',
        'method' => 'post',
//        'enableAjaxValidation' => true,
        'enableClientValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true,
            'validateOnChange' => true
        ),
        'htmlOptions' => array(
            'enctype' => 'multipart/form-data',
            'autocomplete' => 'off',
//            'onsubmit' => 'return true',
        ),
    )); ?>
    <div class="form-group row">
        <div class="col-md-2">
            <?= $formArticle->labelEx($articleModel, 'name') ?>
        </div>
        <div class="col-md-8">
            <?= $formArticle->textField($articleModel, 'name', array('class' => 'fieldInput', 'placeholder' => 'О сайте')); ?>
            <?= $formArticle->error($articleModel, 'name', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            <?= $formArticle->labelEx($articleModel, 'image'); ?>
        </div>
        <div class="col-md-8">
            <?php
                if($articleModel->image) $image = Yii::app()->request->baseUrl.'/upload/articles/' . $articleModel->image; else $image = Yii::app()->request->baseUrl.'/assets/images/blankPhoto1.png';
            ?>
            <div id="image" class="fieldInput" <?= 'style="background-image:url('.$image.')"'; ?>)>
                <?= $formArticle->fileField($articleModel, 'image'); ?>
            </div>
            <?= $formArticle->labelEx($articleModel, 'Размер картинки не может превышать 5 MB') ?>
            <?= $formArticle->error($articleModel, 'image', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            Категория
        </div>
        <div class="col-md-8">
            <?php
            array($articleModel->idCategory => array('selected'=>true));

            $arrayIdCategories = explode(',',$articleModel->idCategory);
            $arrayCategories = array();

            for($i=0;$i<count($arrayIdCategories);$i++){
                $arrayCategories[$arrayIdCategories[$i]] = array('selected'=>true);
            }
            ?>
            <?= $formArticle->dropDownList($categoryModel, 'name', CHtml::listData(Category::model()->findAll(), 'id', 'name', 'category'), array('class' => 'fieldInput', 'multiple'=>'multiple', 'options' => $arrayCategories)); ?>
            <?= $formArticle->error($categoryModel, 'name', array('class' => 'text-red')) ?>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-2">
            <?= $formArticle->labelEx($articleModel, 'text') ?>
        </div>
        <div class="col-md-8">
            <?= $formArticle->textArea($articleModel, 'text', array('class' => 'fieldInput')); ?>
            <?= $formArticle->error($articleModel, 'text', array('class' => 'text-red')) ?>
        </div>
    </div>
    <?= $formArticle->hiddenField($articleModel, 'id', array('class' => 'fieldInput', 'value'=>$articleModel->id)); ?>
    <div class="form-group row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <?= CHtml::submitButton('Сохранить статью', array('class' => 'button1 button1reg')); ?>
        </div>
    </div>
    <?php $this->endWidget(); ?>
</div>
<script src="//cdn.ckeditor.com/4.5.4/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('Article[text]');
</script>

protected/views/articles/index.php
<?php
/* @var $this TestController */
/* @var $dataProvider CActiveDataProvider */

?>
<link href='<?= Yii::app()->request->baseUrl ?>/assets/styles/rating.css' media="screen" rel="stylesheet"
      type="text/css"/>
<script type="text/javascript" src='<?= Yii::app()->request->baseUrl ?>/assets/scripts/rating.js'></script>
<? Yii::app()->clientScript->registerScript('search', "
$('.search-form form').submit(function(){
$.fn.yiiListView.update('articleslistview', {
//this entire js section is taken from admin.php. w/only this line diff
data: $(this).serialize()
});
return false;
});
");
?>
<div id="postAdvert" class="col-md-10">
<?php if(isset($model))
    $this->renderPartial('_search',array(
        'model'=>$model,
    ));
?>

<span id="listOfArticles">
<?php
/*
if(isset($dataProvider)) {
    die('dataprovider');
    $dataProvider->sort->defaultOrder = 'time DESC';
    $this->widget('zii.widgets.CListView', array(
        'dataProvider' => $dataProvider,
        'itemView' => '_view',
        'id' => 'articleslistview',
        'template' => '{sorter}{items}{pager}',
        /*
        'sortableAttributes' => array(
            'time',
            'avg_rating'
        ),

    ));
}
*/
if(isset($articles)) {
    $articles->sort->defaultOrder = 'time DESC';
    $this->widget('zii.widgets.CListView', array(
        'dataProvider' => $articles,
        'itemView' => '_view',
        'id' => 'articleslistview',
        'template' => '{sorter}{items}{pager}',
        /*
        'sortableAttributes' => array(
            'time',
            'avg_rating'
        ),
        */
    ));
}
?>
</span>
</div>