protected/models/Questions.php
<?php

/**
 * This is the model class for table "questions".
 *
 * The followings are the available columns in table 'questions':
 * @property integer $idQuestion
 * @property integer $idPoll
 * @property string $text
 * @property string $description
 */
class Questions extends CActiveRecord
{
    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'questions';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
// NOTE: you should only define rules for those attributes that
// will receive user inputs.
        return array(
            array('idPoll, text, description', 'required'),
            array('idPoll', 'numerical', 'integerOnly' => true),
// The following rule is used by search().
// @todo Please remove those attributes that should not be searched.
            array('idQuestion, idPoll, text, description', 'safe', 'on' => 'search'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
// NOTE: you may need to adjust the relation name and the related
// class name for the relations automatically generated below.
        return array(
            'answers' => array(self::HAS_MANY, 'PossibleAnswer', 'idQuestion'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'idQuestion' => 'Id Question',
            'idPoll' => 'Id Poll',
            'text' => 'Текст вопроса',
            'description' => 'Описание вопроса',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
// @todo Please modify the following code to remove attributes that should not be searched.

        $criteria = new CDbCriteria;

        $criteria->compare('idQuestion', $this->idQuestion);
        $criteria->compare('idPoll', $this->idPoll);
        $criteria->compare('text', $this->text, true);
        $criteria->compare('description', $this->description, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Questions the static model class
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }
}

protected/controllers/QuestionsController.php
<?php

class QuestionsController extends CController
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/admin';
    public $breadCrumbs,
        $menu,
        $nameController = 'Вопросы';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        if (User::isAdmin()) {
            $this->render('view', array(
                'model' => $this->loadModel($id),
            ));
        } else $this->redirect(Yii::app()->request->getBaseUrl(true) . '/site/login');
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        if (User::isAdmin()) {
            if (isset($_GET['id'])) {
                $id = $_GET['id'];
                $poll = Polls::model()->findByPk($id);
                $name = $poll['name'];
            }
            $model = new Questions;

            // Uncomment the following line if AJAX validation is needed
            // $this->performAjaxValidation($model);

            if (isset($_POST['Questions'])) {
                $model->attributes = $_POST['Questions'];
                if ($model->save()) {
                    if (isset($_POST['Answers'])) {
                        foreach ($_POST['Answers'] as $value) {
                            $answers = new PossibleAnswer();
                            $answers->idQuestion = $model->idQuestion;
                            $answers->text = $value;
                            $answers->save();
                        }
                    }
                    $this->redirect(array('admin', 'id' => $model->idPoll));
                }

            }


            $this->render('create', array(
                'model' => $model,
                'name' => $name,
                'id' => $id,
            ));
        } else $this->redirect(Yii::app()->request->getBaseUrl(true) . '/site/login');
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id,$idPoll)
    {
        if (User::isAdmin()) {
            $model = $this->loadModel($id);
            $answers = PossibleAnswer::model()->findAll('idQuestion=:idQuestion', array(':idQuestion'=>$id));
            // Uncomment the following line if AJAX validation is needed
            // $this->performAjaxValidation($model);

            if (isset($_POST['Questions'])) {
                $model->attributes = $_POST['Questions'];
                if ($model->save()){
                    if (isset($_POST['Answers'])) {
                        PossibleAnswer::model()->deleteAllByAttributes(array('idQuestion'=>$id));
                        foreach ($_POST['Answers'] as $value) {
                            $answers = new PossibleAnswer();
                            $answers->idQuestion = $model->idQuestion;
                            $answers->text = $value;
                            $answers->save();
                        }
                    }
                    $this->redirect(array('admin', 'id' => $idPoll));
                }

            }
        } else $this->redirect(Yii::app()->request->getBaseUrl(true) . '/site/login');
        $this->render('update', array(
            'model' => $model,
            'answers'=>$answers,
            'id' => $idPoll,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if (User::isAdmin()) {
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if (!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        } else $this->redirect(Yii::app()->request->getBaseUrl(true) . '/site/login');
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        if (User::isAdmin()) {
            $dataProvider = new CActiveDataProvider('Questions');
            $this->render('index', array(
                'dataProvider' => $dataProvider,
            ));
        } else $this->redirect(Yii::app()->request->getBaseUrl(true) . '/site/login');
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        if (User::isAdmin()) {
            if (isset($_GET['id'])) {
                $id = $_GET['id'];
                $poll = Polls::model()->findByPk($id);
                $name = $poll['name'];
            }
            $model = new Questions('search');
            $model->unsetAttributes();  // clear any default values
            if (isset($_GET['Questions']))
                $model->attributes = $_GET['Questions'];
            $model->idPoll = $id;
            $this->render('admin', array(
                'model' => $model, 'name' => $name, 'id' => $id,
            ));
        } else $this->redirect(Yii::app()->request->getBaseUrl(true) . '/site/login');
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Questions the loaded model
     * @throws CHttpException
     */
    public function loadModel($id)
    {
        $model = Questions::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Questions $model the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'questions-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

protected/views/questions/_form.php
<?php
/* @var $this QuestionsController */
/* @var $model Questions */
/* @var $form CActiveForm */
?>

<div class="form">

    <?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'questions-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

    <div class="row">
        <div class="col-md-6 createGood">
            <div class="box box-primary">
                <div class="box-header with-border">
                </div>
                <div class="box-body">

                    <?php echo $form->errorSummary($model); ?>

                    <div class="form-group">
                        <?php echo $form->hiddenField($model,'idPoll',['value'=>$id]); ?>
                        <?php echo $form->error($model,'idPoll'); ?>
                    </div>

                    <div class="form-group">
                        <?php echo $form->labelEx($model,'text'); ?><br>
                        <?php echo $form->textArea($model,'text',array('rows'=>6, 'cols'=>50)); ?>
                        <?php echo $form->error($model,'text'); ?>
                    </div>

                    <div class="form-group">
                        <?php echo $form->labelEx($model,'description'); ?><br>
                        <?php echo $form->textArea($model,'description',array('rows'=>6, 'cols'=>50)); ?>
                        <?php echo $form->error($model,'description'); ?>
                    </div>

                    <button onclick="addQuestion()" id="addAnswer" type="button">Добавить ответ</button><br><br>
                    <div id="allAnswers">
                        <? if (isset($answers)) {
                            foreach ($answers as $data) {?>
                                <label class="answer<?=$data->idAnswer;?>">Ответ</label>
                                <div class="form-group">
                                    <input class="answer<?=$data->idAnswer;?>" name="Answers[answer<?=$data->idAnswer;?>]" type="text" value="<?=$data->text;?>"/>
                                    <a onclick="removeAnswer(this)" id="answer<?=$data->idAnswer;?>" class="fa fa-ban delete-fa"></a>
                                </div>
                            <?}
                        } else { ?>
                            <label class="answer1">Ответ</label>
                            <div class="form-group">
                                <input class="answer1" name="Answers[answer1]" type="text"/>
                                <a onclick="removeAnswer(this)" id="answer1" class="fa fa-ban delete-fa"></a>
                            </div>
                        <?}?>
                    </div>
                    <div class="row buttons text-center">
                        <?php echo CHtml::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить'); ?>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <?php $this->endWidget(); ?>

</div><!-- form -->
<script src="//cdn.ckeditor.com/4.5.4/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('Questions[description]');
    var crutchForCKEditor = function(){
        var abc = document.getElementsByTagName('iframe')[0].contentDocument;
        var abc2 = abc.childNodes[1];
        var text = abc2.childNodes[1].childNodes[0].innerHTML;
        if(text != '<br>')
            $('#Questions_description').val(text);
    }
    <? if (isset($answers)) {?>
        var iAnswer = parseInt("<? echo($data->idAnswer)?>") + 1;
    <?} else {?>
        var iAnswer = 2;
    <?}?>
    function removeAnswer(object) {
        $('.'+$(object).attr('id')).remove();
        $(object).remove();
    }
    function addQuestion() {
        $('#allAnswers').append('<label class="answer'+iAnswer+'">Ответ</label> <div class="form-group"> <input  class="answer'+iAnswer+'" name="Answers[answer'+iAnswer+']" type="text" > <a onclick="removeAnswer(this)" id="answer'+iAnswer+'" class="fa fa-ban delete-fa"></a> </div>   ');
        iAnswer++;
    }
</script>

protected/views/questions/_search.php
<?php
/* @var $this QuestionsController */
/* @var $model Questions */
/* @var $form CActiveForm */
?>

<div class="wide form">

    <?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

                    <div class="row">
            <?php echo $form->label($model,'idQuestion'); ?>
            <?php echo $form->textField($model,'idQuestion'); ?>
        </div>

                    <div class="row">
            <?php echo $form->label($model,'idPoll'); ?>
            <?php echo $form->textField($model,'idPoll'); ?>
        </div>

                    <div class="row">
            <?php echo $form->label($model,'text'); ?>
            <?php echo $form->textArea($model,'text',array('rows'=>6, 'cols'=>50)); ?>
        </div>

                    <div class="row">
            <?php echo $form->label($model,'description'); ?>
            <?php echo $form->textArea($model,'description',array('rows'=>6, 'cols'=>50)); ?>
        </div>

        <div class="row buttons">
        <?php echo CHtml::submitButton('Search'); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/questions/_view.php
<?php
/* @var $this QuestionsController */
/* @var $data Questions */
?>

<div class="view">

    	<b><?php echo CHtml::encode($data->getAttributeLabel('idQuestion')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->idQuestion), array('view', 'id'=>$data->idQuestion)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('idPoll')); ?>:</b>
	<?php echo CHtml::encode($data->idPoll); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('text')); ?>:</b>
	<?php echo CHtml::encode($data->text); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b>
	<?php echo CHtml::encode($data->description); ?>
	<br />


</div>

protected/views/questions/admin.php
<?php
/* @var $this QuestionsController */
/* @var $model Questions */

$this->breadCrumbs=array(
	'Questions'=>array('index'),
	'Manage',
);
$this->menu=array(
array('label'=>'List Questions', 'url'=>array('index')),
array('label'=>'Create Questions', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$('#questions-grid').yiiGridView('update', {
data: $(this).serialize()
});
return false;
});
");
?>

<h1>Управление вопросами</h1>

<div class="row">
	<div class="col-md-12">
		<div class="box box-info">
			<div class="box-header with-border ui-sortable-handle">
				<h3 class="box-title">Список вопросов для <?='"'.$name.'"';?></h3><br><br>
				<a href="../create/<?=$id;?>">Создать новый вопрос</a>
				<div class="box-tools pull-right">
					<button type="button" class="btn btn-box-tool" data-widget="collapse">
						<i class="fa fa-minus"></i></button>
					<button type="button" class="btn btn-box-tool" data-widget="remove">
						<i class="fa fa-times"></i></button>
				</div>
			</div>
			<div class="box-body">
				<?php $this->widget('zii.widgets.grid.CGridView', array(
					'id'=>'questions-grid',
					'dataProvider'=>$model->search(),
					'filter'=>$model,
					'cssFile' => Yii::app()->request->getBaseUrl(true) . '/assets/admin/css/gridview.css',
					'itemsCssClass' => 'table no-margin',
					'htmlOptions' => array(
						'class' => 'table-responsive'
					),
					'columns'=>array(
						'idQuestion',
						'idPoll',
						'text',
						'description',
						array(
							'class'=>'CButtonColumn',
							'buttons'=>array(
								'update'=> array (
									'options'=>array('class'=>'update'),
									'imageUrl'=>'/assets/f086fb1a/gridview/update.png',
									'url'=>'Yii::app()->createUrl("/questions/update", array("id"=>$data->idQuestion, "idPoll"=>$data->idPoll))',
								),
							),
						),
					),
				)); ?>
			</div>
		</div>
	</div>
</div>

protected/views/questions/create.php
<?php
/* @var $this QuestionsController */
/* @var $model Questions */

$this->breadCrumbs=array(
	'Questions'=>array('index'),
	'Create',
);

$this->menu=array(
array('label'=>'Список вопросов', 'url'=>array('index')),
array('label'=>'Управление вопросами', 'url'=>array('admin')),
);
?>

<h1>Создать вопросы для "<? echo $name?>"</h1>

<?php $this->renderPartial('_form', array('model'=>$model, 'id'=>$id)); ?>

protected/views/questions/index.php
<?php
/* @var $this QuestionsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadCrumbs=array(
	'Questions',
);

$this->menu=array(
array('label'=>'Создать вопросы', 'url'=>array('create')),
array('label'=>'Управление вопросами', 'url'=>array('admin')),
);
?>

<h1>Вопросы</h1>

<?php $this->widget('zii.widgets.CListView', array(
'dataProvider'=>$dataProvider,
'itemView'=>'_view',
)); ?>

protected/views/questions/update.php
<?php
    /* @var $this QuestionsController */
    /* @var $model Questions */

$this->breadCrumbs=array(
	'Questions'=>array('index'),
	$model->idQuestion=>array('view','id'=>$model->idQuestion),
	'Update',
);

    $this->menu=array(
    array('label'=>'Список вопросов', 'url'=>array('index')),
    array('label'=>'Создать вопрос', 'url'=>array('create')),
    array('label'=>'Просмотр вопросов', 'url'=>array('view', 'id'=>$model->idQuestion)),
    array('label'=>'Управление вопросоами', 'url'=>array('admin')),
    );
    ?>

    <h1>Изменить вопросы для <?php echo $model->text; ?></h1>

<? $this->renderPartial('_form', array('model'=>$model, 'answers'=>$answers, 'id'=>$id)); ?>

protected/views/questions/view.php
<?php
/* @var $this QuestionsController */
/* @var $model Questions */

$this->breadCrumbs=array(
	'Questions'=>array('index'),
	$model->idQuestion,
);

$this->menu=array(
array('label'=>'List Questions', 'url'=>array('index')),
array('label'=>'Create Questions', 'url'=>array('create')),
array('label'=>'Update Questions', 'url'=>array('update', 'id'=>$model->idQuestion)),
array('label'=>'Delete Questions', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->idQuestion),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Questions', 'url'=>array('admin')),
);
?>

<h1>View Questions #<?php echo $model->idQuestion; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
'data'=>$model,
'attributes'=>array(
		'idQuestion',
		'idPoll',
		'text',
		'description',
),
)); ?>